# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-02 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('giftshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2017, 3, 2, 15, 50, 13, 775000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
