# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-22 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftshop', '0002_auto_20170322_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='logo',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
