# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-20 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftshop', '0002_auto_20170320_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phoneNumber',
            field=models.CharField(default='', max_length=16),
        ),
    ]
