# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-20 22:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('giftshop', '0003_auto_20170320_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='addedDate',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='added_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 3, 20, 22, 7, 0, 194157, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
