# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-02 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftshop', '0003_auto_20170302_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
