# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-02 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftshop', '0005_auto_20170302_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
