# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-13 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftshop', '0008_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='itemID',
        ),
        migrations.RemoveField(
            model_name='review',
            name='userID',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
