# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-13 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftshop', '0009_auto_20170313_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
