# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-17 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('giftshop', '0010_item_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='comment_user')),
                ('user_email', models.EmailField(max_length=255, verbose_name='comment_email')),
                ('body', models.TextField(verbose_name='content')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('rating', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='comments',
        ),
        migrations.AddField(
            model_name='review',
            name='itemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftshop.Item'),
        ),
        migrations.AddField(
            model_name='review',
            name='userID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftshop.Item', verbose_name='belong_item'),
        ),
    ]
